export const cardData = [
  {
    balance: 4233,
    name: 'Eddy Cusma',
    validity: '12/01',
    number: '3778 **** *** 1234',
    type: 'paypal',
  },
  {
    balance: 2342,
    name: 'Saren Wanderwoodson',
    validity: '07/26',
    number: '0922 **** **** 1483',
    type: 'debit',
  },
  {
    balance: 9876,
    name: 'Lila Hartmann',
    validity: '03/25',
    number: '5412 **** **** 7890',
    type: 'debit',
  },
  {
    balance: 4567,
    name: 'Marcus Rodriguez',
    validity: '11/24',
    number: '4561 **** *** 2345',
    type: 'paypal',
  },
  {
    balance: 6543,
    name: 'Elena Petrova',
    validity: '09/27',
    number: '1234 **** **** 5678',
    type: 'debit',
  },
  {
    balance: 3210,
    name: 'Jack Thompson',
    validity: '06/23',
    number: '6789 **** *** 9012',
    type: 'paypal',
  },
  {
    balance: 8765,
    name: 'Sophia Chen',
    validity: '04/26',
    number: '2345 **** **** 6789',
    type: 'debit',
  },
  {
    balance: 2109,
    name: "Aiden O'Connor",
    validity: '10/22',
    number: '7890 **** *** 3456',
    type: 'paypal',
  },
  {
    balance: 5432,
    name: 'Isabella Martinez',
    validity: '05/25',
    number: '8901 **** **** 4567',
    type: 'debit',
  },
  {
    balance: 7654,
    name: 'Noah Williams',
    validity: '01/24',
    number: '9012 **** *** 7890',
    type: 'paypal',
  },
  {
    balance: 3456,
    name: 'Emma Johnson',
    validity: '08/26',
    number: '4567 **** **** 2345',
    type: 'debit',
  },
  {
    balance: 6789,
    name: 'Liam Anderson',
    validity: '02/23',
    number: '5678 **** *** 9012',
    type: 'paypal',
  },
  {
    balance: 9012,
    name: 'Olivia Smith',
    validity: '12/25',
    number: '6789 **** **** 3456',
    type: 'debit',
  },
  {
    balance: 2345,
    name: 'Ethan Brown',
    validity: '07/22',
    number: '7890 **** *** 5678',
    type: 'paypal',
  },
  {
    balance: 7890,
    name: 'Ava Davis',
    validity: '03/24',
    number: '8901 **** **** 1234',
    type: 'debit',
  },
  {
    balance: 4321,
    name: 'Mason Taylor',
    validity: '11/23',
    number: '9012 **** *** 6789',
    type: 'paypal',
  },
  {
    balance: 6543,
    name: 'Harper Wilson',
    validity: '06/25',
    number: '1234 **** **** 7890',
    type: 'debit',
  },
  {
    balance: 3210,
    name: 'Logan Moore',
    validity: '09/22',
    number: '2345 **** *** 2345',
    type: 'paypal',
  },
  {
    balance: 8765,
    name: 'Charlotte Lee',
    validity: '04/26',
    number: '3456 **** **** 9012',
    type: 'debit',
  },
  {
    balance: 5678,
    name: 'Lucas Garcia',
    validity: '10/24',
    number: '4567 **** *** 3456',
    type: 'paypal',
  },
  {
    balance: 2109,
    name: 'Amelia Martinez',
    validity: '05/23',
    number: '5678 **** **** 5678',
    type: 'debit',
  },
  {
    balance: 9876,
    name: 'Benjamin Robinson',
    validity: '01/25',
    number: '6789 **** *** 7890',
    type: 'paypal',
  },
  {
    balance: 4567,
    name: 'Mia Clark',
    validity: '08/22',
    number: '7890 **** **** 1234',
    type: 'debit',
  },
  {
    balance: 7123,
    name: 'William Rodriguez',
    validity: '02/24',
    number: '8901 **** *** 6789',
    type: 'paypal',
  },
  {
    balance: 5432,
    name: 'Sofia Thompson',
    validity: '12/23',
    number: '9012 **** **** 3456',
    type: 'debit',
  },
  {
    balance: 3698,
    name: 'James White',
    validity: '07/25',
    number: '1234 **** *** 5678',
    type: 'paypal',
  },
  {
    balance: 6789,
    name: 'Evelyn Harris',
    validity: '03/22',
    number: '2345 **** **** 9012',
    type: 'debit',
  },
  {
    balance: 4321,
    name: 'Daniel Martin',
    validity: '11/24',
    number: '3456 **** *** 2345',
    type: 'paypal',
  },
  {
    balance: 8765,
    name: 'Abigail Lewis',
    validity: '06/26',
    number: '4567 **** **** 7890',
    type: 'debit',
  },
  {
    balance: 2345,
    name: 'Alexander Walker',
    validity: '09/23',
    number: '5678 **** *** 1234',
    type: 'paypal',
  },
];

export const transactionData = [
  {
    id: 1,
    description: 'Deposit from my Card',
    amount: -850,
    date: '28 January 2021',
    platform: 'card',
  },
  {
    id: 2,
    description: 'Deposit Paypal',
    amount: 2500,
    date: '25 January 2021',
    platform: 'paypal',
  },
  {
    id: 3,
    description: 'Jemi Wilson',
    amount: 5400,
    date: '21 January 2021',
    platform: 'other',
  },
  {
    id: 4,
    description: 'Online Shopping',
    amount: -1250,
    date: '15 February 2021',
    platform: 'card',
  },
  {
    id: 5,
    description: 'Freelance Payment',
    amount: 3750,
    date: '10 February 2021',
    platform: 'paypal',
  },
  {
    id: 6,
    description: 'Gift from Grandma',
    amount: 500,
    date: '5 February 2021',
    platform: 'other',
  },
  {
    id: 7,
    description: 'Monthly Subscription',
    amount: -75,
    date: '1 February 2021',
    platform: 'card',
  },
  {
    id: 8,
    description: 'Consulting Work',
    amount: 6200,
    date: '28 January 2021',
    platform: 'paypal',
  },
  {
    id: 9,
    description: 'Birthday Gift',
    amount: 1000,
    date: '20 January 2021',
    platform: 'other',
  },
  {
    id: 10,
    description: 'Grocery Shopping',
    amount: -350,
    date: '15 January 2021',
    platform: 'card',
  },
  {
    id: 11,
    description: 'Ebay Selling',
    amount: 450,
    date: '10 January 2021',
    platform: 'paypal',
  },
  {
    id: 12,
    description: 'Loan Repayment',
    amount: 2000,
    date: '5 January 2021',
    platform: 'other',
  },
  {
    id: 13,
    description: 'Tech Gadget Purchase',
    amount: -1500,
    date: '30 December 2020',
    platform: 'card',
  },
  {
    id: 14,
    description: 'Graphic Design Project',
    amount: 4500,
    date: '25 December 2020',
    platform: 'paypal',
  },
  {
    id: 15,
    description: 'Christmas Gift',
    amount: 750,
    date: '20 December 2020',
    platform: 'other',
  },
  {
    id: 16,
    description: 'Restaurant Dinner',
    amount: -120,
    date: '15 December 2020',
    platform: 'card',
  },
  {
    id: 17,
    description: 'Tutoring Income',
    amount: 1200,
    date: '10 December 2020',
    platform: 'paypal',
  },
  {
    id: 18,
    description: 'Family Support',
    amount: 3000,
    date: '5 December 2020',
    platform: 'other',
  },
  {
    id: 19,
    description: 'Book Purchase',
    amount: -50,
    date: '1 December 2020',
    platform: 'card',
  },
  {
    id: 20,
    description: 'Writing Gig',
    amount: 2750,
    date: '25 November 2020',
    platform: 'paypal',
  },
  {
    id: 21,
    description: 'Random Bonus',
    amount: 1500,
    date: '20 November 2020',
    platform: 'other',
  },
  {
    id: 22,
    description: 'Gas Station',
    amount: -75,
    date: '15 November 2020',
    platform: 'card',
  },
  {
    id: 23,
    description: 'Coaching Session',
    amount: 3250,
    date: '10 November 2020',
    platform: 'paypal',
  },
  {
    id: 24,
    description: 'Prize Money',
    amount: 5000,
    date: '5 November 2020',
    platform: 'other',
  },
  {
    id: 25,
    description: 'Online Course',
    amount: -250,
    date: '1 November 2020',
    platform: 'card',
  },
  {
    id: 26,
    description: 'Translation Work',
    amount: 1800,
    date: '25 October 2020',
    platform: 'paypal',
  },
  {
    id: 27,
    description: 'Rent Refund',
    amount: 2200,
    date: '20 October 2020',
    platform: 'other',
  },
  {
    id: 28,
    description: 'Coffee Shop',
    amount: -15,
    date: '15 October 2020',
    platform: 'card',
  },
  {
    id: 29,
    description: 'Web Development Gig',
    amount: 4800,
    date: '10 October 2020',
    platform: 'paypal',
  },
  {
    id: 30,
    description: 'Investment Return',
    amount: 6500,
    date: '5 October 2020',
    platform: 'other',
  },
];

export const expenseCategories = [
  'entertainment',
  'investment',
  'billExpenses',
  'others',
];

export const usersData = [
  {
    name: 'Livia Bator',
    role: 'CEO',
    image: '/src/assets/images/profile-4.jpg',
  },
  {
    name: 'Randy Press',
    role: 'Director',
    image: '/src/assets/images/profile-2.jpg',
  },
  {
    name: 'Emily Stone',
    role: 'Designer',
    image: '/src/assets/images/profile-3.jpg',
  },
  {
    name: 'James Bond',
    role: 'Developer',
    image: '/src/assets/images/profile-2.jpg',
  },
  {
    name: 'Oliver Quick',
    role: 'Manager',
    image: '/src/assets/images/profile-4.jpg',
  },
  {
    name: 'Sophia Turner',
    role: 'HR',
    image: '/src/assets/images/profile-3.jpg',
  },
  {
    name: 'Ethan Hunt',
    role: 'Accountant',
    image: '/src/assets/images/profile-4.jpg',
  },
  {
    name: 'Amelia Rose',
    role: 'Marketing Lead',
    image: '/src/assets/images/profile-2.jpg',
  },
  {
    name: 'Noah Finch',
    role: 'Product Manager',
    image: '/src/assets/images/profile-3.jpg',
  },
  {
    name: 'Ella Parker',
    role: 'Sales Lead',
    image: '/src/assets/images/profile-4.jpg',
  },
  {
    name: 'Aiden Wolf',
    role: 'Designer',
    image: '/src/assets/images/profile-2.jpg',
  },
  {
    name: 'Grace Lee',
    role: 'Engineer',
    image: '/src/assets/images/profile-3.jpg',
  },
  {
    name: 'Lucas King',
    role: 'CEO',
    image: '/src/assets/images/profile-2.jpg',
  },
  { name: 'Mia Bell', role: 'CTO', image: '/src/assets/images/profile-4.jpg' },
  {
    name: 'Jack Miller',
    role: 'Director',
    image: '/src/assets/images/profile-3.jpg',
  },
  {
    name: 'Olivia Scott',
    role: 'Designer',
    image: '/src/assets/images/profile-4.jpg',
  },
  {
    name: 'Samuel Davis',
    role: 'Support Lead',
    image: '/src/assets/images/profile-3.jpg',
  },
  {
    name: 'Zoe Adams',
    role: 'Marketing',
    image: '/src/assets/images/profile-2.jpg',
  },
  {
    name: 'Benjamin Clark',
    role: 'Developer',
    image: '/src/assets/images/profile-4.jpg',
  },
  {
    name: 'Chloe Walker',
    role: 'HR',
    image: '/src/assets/images/profile-3.jpg',
  },
  {
    name: 'Daniel Johnson',
    role: 'Sales',
    image: '/src/assets/images/profile-2.jpg',
  },
  {
    name: 'Isabella Wright',
    role: 'Designer',
    image: '/src/assets/images/profile-4.jpg',
  },
  {
    name: 'Michael Carter',
    role: 'Manager',
    image: '/src/assets/images/profile-3.jpg',
  },
  {
    name: 'Samuel Evans',
    role: 'Product Lead',
    image: '/src/assets/images/profile-2.jpg',
  },
  {
    name: 'Harper Green',
    role: 'Project Manager',
    image: '/src/assets/images/profile-3.jpg',
  },
  {
    name: 'Liam Harris',
    role: 'Software Engineer',
    image: '/src/assets/images/profile-4.jpg',
  },
  {
    name: 'Charlotte Lewis',
    role: 'Designer',
    image: '/src/assets/images/profile-2.jpg',
  },
  {
    name: 'Evan White',
    role: 'Marketing',
    image: '/src/assets/images/profile-4.jpg',
  },
  {
    name: 'Ella Brown',
    role: 'Developer',
    image: '/src/assets/images/profile-3.jpg',
  },
];

export const monthNames = [
  'Jan',
  'Feb',
  'Mar',
  'Apr',
  'May',
  'Jun',
  'Jul',
  'Aug',
  'Sep',
  'Oct',
  'Nov',
  'Dec',
];
